<a href="https://colab.research.google.com/github/Camolas/ML_DOC/blob/master/Experi%C3%AAncias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [16]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
#! pip install pandas
#! conda env list
#df = pd.read_csv("ComaSessions.csv")
#df.head()

In [5]:
url = 'https://raw.githubusercontent.com/Camolas/ML_DOC/master/Databases/SmartAvaliationPrototype.csv'

In [6]:
from numpy import genfromtxt
my_data = genfromtxt('https://raw.githubusercontent.com/Camolas/ML_DOC/master/Databases/SmartAvaliationPrototype.csv', delimiter=',')

In [7]:
docDF = pd.read_csv(url)

In [8]:
type(docDF)

pandas.core.frame.DataFrame

In [9]:
docDF.head()

   Order  ID  ...  BothRatersSession10  BothRatersCertainty10
0      1   1  ...                    2                    100
1      2   2  ...                    2                    100
2      3   3  ...                    2                    100
3      4   4  ...                    1                     80
4      5   5  ...                    2                    100

[5 rows x 148 columns]

In [17]:
docDF.shape #We have 35 lines and 148 columns of data

(35, 148)

In [10]:
print(my_data)

[[ nan  nan  nan ...  nan  nan  nan]
 [  1.   1.   1. ... 100.   2. 100.]
 [  2.   2.   2. ... 100.   2. 100.]
 ...
 [ 33.  50.   2. ... 100.   2. 100.]
 [ 34.  51.   2. ... 100.   2. 100.]
 [ 35.  52.   2. ... 100.   2. 100.]]

In [11]:
docDF.describe()

           Order         ID  ...  BothRatersSession10  BothRatersCertainty10
count  35.000000  35.000000  ...            35.000000              35.000000
mean   18.000000  29.000000  ...             1.685714              98.571429
std    10.246951  16.615018  ...             0.471008               4.936572
min     1.000000   1.000000  ...             1.000000              80.000000
25%     9.500000  14.000000  ...             1.000000             100.000000
50%    18.000000  33.000000  ...             2.000000             100.000000
75%    26.500000  42.500000  ...             2.000000             100.000000
max    35.000000  52.000000  ...             2.000000             100.000000

[8 rows x 132 columns]

In [18]:
docDF.info() # as we have a lot of Columns We don't describe (numerating, describing, and secure non-Null Count, see Dtype)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Columns: 148 entries, Order to BothRatersCertainty10
dtypes: int64(132), object(16)
memory usage: 40.6+ KB

# Machine Learning

In [13]:
docDF['Diagnostic'].value_counts()

2    25
1    10
Name: Diagnostic, dtype: int64

In [14]:
docDF

    Order  ID  ...  BothRatersSession10  BothRatersCertainty10
0       1   1  ...                    2                    100
1       2   2  ...                    2                    100
2       3   3  ...                    2                    100
3       4   4  ...                    1                     80
4       5   5  ...                    2                    100
5       6   6  ...                    2                    100
6       7   7  ...                    1                    100
7       8   8  ...                    2                    100
8       9   9  ...                    1                    100
9      10  19  ...                    2                     90
10     11  22  ...                    2                    100
11     12  23  ...                    2                    100
12     13  25  ...                    2                    100
13     14  26  ...                    2                    100
14     15  28  ...                    2                    100
15     16  29  ...                    2                    100
16     17  32  ...                    2                    100
17     18  33  ...                    2                    100
18     19  34  ...                    1                    100
19     20  35  ...                    1                    100
20     21  36  ...                    1                    100
21     22  38  ...                    2                    100
22     23  39  ...                    2                    100
23     24  40  ...                    1                    100
24     25  41  ...                    2                    100
25     26  42  ...                    1                    100
26     27  43  ...                    1                    100
27     28  44  ...                    2                    100
28     29  45  ...                    1                    100
29     30  46  ...                    1                    100
30     31  48  ...                    2                    100
31     32  49  ...                    2                     80
32     33  50  ...                    2                    100
33     34  51  ...                    2                    100
34     35  52  ...                    2                    100

[35 rows x 148 columns]

In [15]:
docDF.isnull().sum() #Missing values flagged by NA

Order                    0
ID                       0
Sex                      0
Age                      0
Etiology                 0
                        ..
BothRatersCertainty8     0
BothRatersSession9       0
BothRatersCertainty9     0
BothRatersSession10      0
BothRatersCertainty10    0
Length: 148, dtype: int64

In [15]:
docDF[df]