<a href="https://colab.research.google.com/github/ManJ-PC/ML_DOC/blob/master/ML_DOC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
url = 'https://raw.githubusercontent.com/Camolas/ML_DOC/master/Databases/SmartAvaliationPrototype.csv'

In [ ]:
df1 = pd.read_csv(url)

In [ ]:
df1.head()

   Order  ID  ...  BothRatersSession10  BothRatersCertainty10
0      1   1  ...                    2                    100
1      2   2  ...                    2                    100
2      3   3  ...                    2                    100
3      4   4  ...                    1                     80
4      5   5  ...                    2                    100

[5 rows x 148 columns]

In [ ]:
from numpy import genfromtxt
my_data = genfromtxt('https://raw.githubusercontent.com/Camolas/ML_DOC/master/Databases/SmartAvaliationPrototype.csv', delimiter=',')

In [ ]:
print(my_data)

[[ nan  nan  nan ...  nan  nan  nan]
 [  1.   1.   1. ... 100.   2. 100.]
 [  2.   2.   2. ... 100.   2. 100.]
 ...
 [ 33.  50.   2. ... 100.   2. 100.]
 [ 34.  51.   2. ... 100.   2. 100.]
 [ 35.  52.   2. ... 100.   2. 100.]]