<a href="https://colab.research.google.com/github/Camolas/ML_DOC/blob/master/InitialExperiments/Experi%C3%AAncias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#! pip install pandas
#! conda env list
#df = pd.read_csv("ComaSessions.csv")
#df.head()

In [5]:
url = 'https://raw.githubusercontent.com/Camolas/ML_DOC/master/Databases/SmartAvaliationPrototype.csv'

In [8]:
from numpy import genfromtxt
my_data = genfromtxt('https://raw.githubusercontent.com/Camolas/ML_DOC/master/Databases/SmartAvaliationPrototype.csv', delimiter=',')

In [6]:
df1 = pd.read_csv(url)

In [10]:
type(df1)

pandas.core.frame.DataFrame

In [7]:
df1.head()

   Order  ID  ...  BothRatersSession10  BothRatersCertainty10
0      1   1  ...                    2                    100
1      2   2  ...                    2                    100
2      3   3  ...                    2                    100
3      4   4  ...                    1                     80
4      5   5  ...                    2                    100

[5 rows x 148 columns]

In [9]:
print(my_data)

[[ nan  nan  nan ...  nan  nan  nan]
 [  1.   1.   1. ... 100.   2. 100.]
 [  2.   2.   2. ... 100.   2. 100.]
 ...
 [ 33.  50.   2. ... 100.   2. 100.]
 [ 34.  51.   2. ... 100.   2. 100.]
 [ 35.  52.   2. ... 100.   2. 100.]]

In [12]:
df1.describe()

           Order         ID  ...  BothRatersSession10  BothRatersCertainty10
count  35.000000  35.000000  ...            35.000000              35.000000
mean   18.000000  29.000000  ...             1.685714              98.571429
std    10.246951  16.615018  ...             0.471008               4.936572
min     1.000000   1.000000  ...             1.000000              80.000000
25%     9.500000  14.000000  ...             1.000000             100.000000
50%    18.000000  33.000000  ...             2.000000             100.000000
75%    26.500000  42.500000  ...             2.000000             100.000000
max    35.000000  52.000000  ...             2.000000             100.000000

[8 rows x 132 columns]

# Machine Learning

In [11]:
type

type